config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  get 'auth/:provider/callback', to: 'googles#create'
  get 'auth/failure', to: redirect('/')

  resources :users
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts
    resource :feed
    resources :users
    resources :follows
    resources :likes
    resources :comments
    get "search", to: "searches#index"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :require_signed_in

  def root
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/root.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400' rel='stylesheet' type='text/css'>

<header class="header">
  <nav class="header-nav group">

    <ul class="header-left-list group">
      <li><a href="#"><i class="fa fa-home"></i></a></li>
      <li><a href="#search"><i class="fa fa-search"></i></a></li>
      <li><a href="#upload"><i class="fa fa-camera-retro fa-lg"></i></a></li>
    </ul>

    <div class="header-logo">
      <a href="#">Vinstagram</a>
    </div>

    <div class="header-right">
      <a href="#user/<%= current_user.id %>" class="header-right"><%= current_user.username %></a><br>
      <ul class="dropdown">
        <li><a href="#user/<%= current_user.id %>">My Profile</a></li>
        <li><a href="#settings">Settings</a></li>
        <li><%= link_to "Sign out", session_url, :method => :delete %></li>
      </ul>
    </div>

    </section>

  </nav>
</header>

<div id="main">
  <!-- this is where were rendering backbone -->
</div>

<footer class="footer">
</footer>

<script>
  $(document).ready(function(){
    Vinstagram.initialize();
  });
</script>