config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  get 'auth/:provider/callback', to: 'googles#create'
  get 'auth/failure', to: redirect('/')

  resources :users
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts
    resource :feed
    resources :users
    resources :follows
    resources :likes
    resources :comments
    get "search", to: "searches#index"
  end

end

app/models/User.rb
class User < ActiveRecord::Base

  has_attached_file :picture, default_url: "default.png", :styles => { :small => '156x156', :thumb => '100x100' }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  include PgSearch
  pg_search_scope :user_search,
                  against: [:username],
                  using: { tsearch: {:prefix => true} }


  validates :username, :email, :password_digest, :session_token, presence: true
  validates :username, length: { maximum: 14 }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :email, uniqueness: { case_sensitive: false }

  validates :password, confirmation: true
  validates :password_confirmation, presence: { :on => :create }

  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  ################################################

  # People That I follow
  has_many(
    :follows,
    class_name: "Follow",
    foreign_key: :follower_id,
    primary_key: :id
  )

  has_many(
    :followees,
    through: :follows,
    source: :followee
  )

  ################################################

  # People that Follow Me
  has_many(
    :followings,
    class_name: "Follow",
    foreign_key: :followee_id,
    primary_key: :id
  )

  has_many(
    :followers,
    through: :followings,
    source: :follower
  )

  ################################################

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :likes,
    class_name: "Like",
    foreign_key: :liker_id,
    primary_key: :id
  )

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]

      temp = ""
      auth['info']['email'].each_char do |char|
        break if char == "@"
        temp << char
      end

      user.username = temp.first(14)

      user.email = auth["info"]["email"]
      user.password = "default"
      user.password_confirmation = "default"
    end

  end

  def feed_posts(page_num)

    followees = self.followees

    followed_user_ids = [self.id]
    followees.each do |user|
     followed_user_ids << user.id
    end

    Post.includes(
      :author,
      :likes,
      :likers,
      comments: [:author])
      .where("author_id IN (?)", followed_user_ids)
      .order(created_at: :desc).page(page_num).per(4)
  end

  def num_followers
    followers.count
  end

  def num_followees
    followees.count
  end

  ################################################

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController

    def index
      # Using this for fetching the current user for settings!
      @user = current_user
      render :index
    end

    def show
      @user = User.includes(:posts).find(params[:id])
      render :show
    end

    def update
      @user = current_user

      @user.bio = (params[:user][:bio])

      if(params[:user][:picture])
        @user.picture = (params[:user][:picture])
      end

      if @user.save
        render json: @user
      else
        render json: @user.errors.full_messages, status: 422
      end

    end

    private
    def user_params
      params.require(:user).permit(:picture, :bio)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signed_out

  def new
    if (!@user)
       @user = User.new
     end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<title>Sign Up! Vinstagram</title>

<div class="welcome">

  <div class="form-header">
    <div class="logo">Vinstagram</div>
  </div>
  <div class="form">

    <% if flash[:errors] %>
      <%= flash[:errors].join("<br>").html_safe %>
      <br><br>
    <% end %>

    <form action="<%= users_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <section class="sign-first">
        <label>Username:</label>
        <input tabindex="1" type="text" name="user[username]" value="<%= @user.username %>">
      </section>

      <section class="sign-nth">
        <label>Email:</label>
        <input tabindex="2" type="text" name="user[email]" value="<%= @user.email %>">
      </section>

      <section class="sign-nth">
        <label> Password:
        <input tabindex="3" type="password" name="user[password]" value="">
      </section>

      <section class="sign-nth">
        <label> Confirm Password:
        <input tabindex="4" type="password" name="user[password_confirmation]" value="">
      </section>

      <section class="sign-bottom group">
        <label>
          Already Registered? <br>
          <u><%= link_to "Sign In!", new_session_url %></u>
        </label>
        <input tabindex="5" type="submit" class="button" value="Sign Up!">
      </section>

    </form>
  </div>

  <div class="guest-login group">
    <div class="top-label">
      Don't want to create an account yet?
    </div>

    <label>
      Check out our guest account on our <u><%= link_to "login page", new_session_url %></u>
    </label>

    <br><br>

    <br>
    <div class="Or">
    </div>
    <br>

  <div class="google-sign-in">
    <a href="/auth/google_oauth2" id="google-sign-in">
      <img src="https://developers.google.com/accounts/images/sign-in-with-google.png" alt="" />
    </a>
  </div>


  </div>



</div>